#include "../include/uart_keyboard_asciimap.h"

const AsciiMap asciiMapList[ASCII_MAP_SIZE] = {
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x2F}, .none=new TypeCode{.type=CHAR, .code='v'}, .shift=new TypeCode{.type=CHAR, .code='V'}, .alt=NULL, .strg=new TypeCode{.type=EVENT, .code=KB_EVENT_PAST}, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 00 - V
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x20}, .none=new TypeCode{.type=CHAR, .code='d'}, .shift=new TypeCode{.type=CHAR, .code='D'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 01 - D
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x21}, .none=new TypeCode{.type=CHAR, .code='f'}, .shift=new TypeCode{.type=CHAR, .code='F'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 02 - F
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x2E}, .none=new TypeCode{.type=CHAR, .code='c'}, .shift=new TypeCode{.type=CHAR, .code='C'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 03 - C
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x12}, .none=new TypeCode{.type=CHAR, .code='e'}, .shift=new TypeCode{.type=CHAR, .code='E'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 04 - E
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x01}, .none=new TypeCode{.type=CHAR, .code=0x1B}, .shift=new TypeCode{.type=CHAR, .code=0x1B}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 05 - ESC
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x13}, .none=new TypeCode{.type=CHAR, .code='r'}, .shift=new TypeCode{.type=CHAR, .code='R'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 06 - R
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x31}, .none=new TypeCode{.type=CHAR, .code='n'}, .shift=new TypeCode{.type=CHAR, .code='N'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 07 - N
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x22}, .none=new TypeCode{.type=CHAR, .code='g'}, .shift=new TypeCode{.type=CHAR, .code='G'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 08 - G
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x23}, .none=new TypeCode{.type=CHAR, .code='h'}, .shift=new TypeCode{.type=CHAR, .code='H'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 09 - H
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x30}, .none=new TypeCode{.type=CHAR, .code='b'}, .shift=new TypeCode{.type=CHAR, .code='B'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 0A - B
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x14}, .none=new TypeCode{.type=CHAR, .code='t'}, .shift=new TypeCode{.type=CHAR, .code='T'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 0B - T
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x56}, .none=new TypeCode{.type=CHAR, .code='<'}, .shift=new TypeCode{.type=CHAR, .code='>'}, .alt=new TypeCode{.type=CHAR, .code='|'}, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 0C - |<>
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x2C}, .none=new TypeCode{.type=CHAR, .code='y'}, .shift=new TypeCode{.type=CHAR, .code='Y'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 0D - Y
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x2D}, .none=new TypeCode{.type=CHAR, .code='x'}, .shift=new TypeCode{.type=CHAR, .code='X'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 0E - X
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x1E}, .none=new TypeCode{.type=CHAR, .code='a'}, .shift=new TypeCode{.type=CHAR, .code='A'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 0F - A
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x1F}, .none=new TypeCode{.type=CHAR, .code='s'}, .shift=new TypeCode{.type=CHAR, .code='S'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 10 - S
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x15}, .none=new TypeCode{.type=CHAR, .code='z'}, .shift=new TypeCode{.type=CHAR, .code='Z'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 11 - Z
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x10}, .none=new TypeCode{.type=CHAR, .code='q'}, .shift=new TypeCode{.type=CHAR, .code='Q'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 12 - Q
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x0F}, .none=new TypeCode{.type=CHAR, .code=0x09}, .shift=NULL, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 13 - TAB
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x11}, .none=new TypeCode{.type=CHAR, .code='w'}, .shift=new TypeCode{.type=CHAR, .code='W'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 14 - W
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x33}, .none=new TypeCode{.type=CHAR, .code=','}, .shift=new TypeCode{.type=CHAR, .code=';'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 15 - ,
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x24}, .none=new TypeCode{.type=CHAR, .code='j'}, .shift=new TypeCode{.type=CHAR, .code='J'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 16 - J
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x25}, .none=new TypeCode{.type=CHAR, .code='k'}, .shift=new TypeCode{.type=CHAR, .code='K'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 17 - K
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x32}, .none=new TypeCode{.type=CHAR, .code='m'}, .shift=new TypeCode{.type=CHAR, .code='M'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 18 - M
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x16}, .none=new TypeCode{.type=CHAR, .code='u'}, .shift=new TypeCode{.type=CHAR, .code='U'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 19 - U
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x29}, .none=new TypeCode{.type=CHAR, .code='^'}, .shift=new TypeCode{.type=CHAR, .code='?'}, .alt=new TypeCode{.type=CHAR, .code='\\'}, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 1A - ^
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x17}, .none=new TypeCode{.type=CHAR, .code='i'}, .shift=new TypeCode{.type=CHAR, .code='I'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 1B - I
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x35}, .none=new TypeCode{.type=CHAR, .code='-'}, .shift=new TypeCode{.type=CHAR, .code='_'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 1C - -
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x08}, .none=new TypeCode{.type=CHAR, .code='7'}, .shift=new TypeCode{.type=CHAR, .code='/'}, .alt=new TypeCode{.type=CHAR, .code='&'}, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 1D - 7
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x05}, .none=new TypeCode{.type=CHAR, .code='4'}, .shift=new TypeCode{.type=CHAR, .code='$'}, .alt=new TypeCode{.type=CHAR, .code='~'}, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 1E - 4
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x02}, .none=new TypeCode{.type=CHAR, .code='1'}, .shift=new TypeCode{.type=CHAR, .code='!'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL},// 1F - 1
    (AsciiMap) {.scancode = (Scancode) {.special = 0xE0, .code = 0x48}, .none=new TypeCode{.type=EVENT, .code=KB_EVENT_ARROWLEFT}, .shift=new TypeCode{.type=EVENT, .code=KB_EVENT_FUNC4}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 20 - ARROW_LEFT
    (AsciiMap) {.scancode = (Scancode) {.special = 0xE0, .code = 0x5F}, .none=new TypeCode{.type=EVENT, .code=KB_EVENT_OFF}, .shift=new TypeCode{.type=EVENT, .code=KB_EVENT_OFF}, .alt=new TypeCode{.type=EVENT, .code=KB_EVENT_OFF}, .strg=new TypeCode{.type=EVENT, .code=KB_EVENT_OFF}, .shiftalt=new TypeCode{.type=EVENT, .code=KB_EVENT_OFF}, .altstrg=new TypeCode{.type=EVENT, .code=KB_EVENT_OFF}, .strgshift=new TypeCode{.type=EVENT, .code=KB_EVENT_OFF}, .strgaltshift=new TypeCode{.type=EVENT, .code=KB_EVENT_OFF}}, // 21 - OFF
    (AsciiMap) {.scancode = (Scancode) {.special = 0xE0, .code = 0x22}, .none=new TypeCode{.type=CHAR, .code=0x7F}, .shift=new TypeCode{.type=EVENT, .code=KB_EVENT_FUNC1}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 22 - Del
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x18}, .none=new TypeCode{.type=CHAR, .code='+'}, .shift=new TypeCode{.type=CHAR, .code='*'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 23 - +
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x26}, .none=new TypeCode{.type=CHAR, .code='l'}, .shift=new TypeCode{.type=CHAR, .code='L'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 24 - L
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x1C}, .none=new TypeCode{.type=CHAR, .code=0x0D}, .shift=new TypeCode{.type=CHAR, .code=0x0D}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 25 - RETURN
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x39}, .none=new TypeCode{.type=CHAR, .code=' '}, .shift=new TypeCode{.type=CHAR, .code=' '}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 26 - SPACE
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x18}, .none=new TypeCode{.type=CHAR, .code='o'}, .shift=new TypeCode{.type=CHAR, .code='O'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 27 - O
    (AsciiMap) {.scancode = (Scancode) {.special = 0xE0, .code = 0x52}, .none=new TypeCode{.type=EVENT, .code=KB_EVENT_INSERT}, .shift=new TypeCode{.type=EVENT, .code=KB_EVENT_INSERT}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 28 - INS
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x19}, .none=new TypeCode{.type=CHAR, .code='p'}, .shift=new TypeCode{.type=CHAR, .code='P'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 29 - P
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x0B}, .none=new TypeCode{.type=CHAR, .code='0'}, .shift=new TypeCode{.type=CHAR, .code='='}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 2A - 0
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x09}, .none=new TypeCode{.type=CHAR, .code='8'}, .shift=new TypeCode{.type=CHAR, .code='('}, .alt=new TypeCode{.type=CHAR, .code='['}, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 2B - 8
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x06}, .none=new TypeCode{.type=CHAR, .code='5'}, .shift=new TypeCode{.type=CHAR, .code='%'}, .alt=new TypeCode{.type=CHAR, .code='{'}, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 2C - 5
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x03}, .none=new TypeCode{.type=CHAR, .code='2'}, .shift=new TypeCode{.type=CHAR, .code='"'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 2D - 2
    (AsciiMap) {.scancode = (Scancode) {.special = 0xE0, .code = 0x50}, .none=new TypeCode{.type=EVENT, .code=KB_EVENT_ARROWDOWN}, .shift=new TypeCode{.type=EVENT, .code=KB_EVENT_FUNC5}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 2E - ARROW_DOWN
    (AsciiMap) {.scancode = (Scancode) {.special = 0xE0, .code = 0x48}, .none=new TypeCode{.type=EVENT, .code=KB_EVENT_ARROWUP}, .shift=new TypeCode{.type=EVENT, .code=KB_EVENT_FUNC2}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 30 - ARROW_UP
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x34}, .none=new TypeCode{.type=CHAR, .code='.'}, .shift=new TypeCode{.type=CHAR, .code=':'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 31 - .
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x0A}, .none=new TypeCode{.type=CHAR, .code='9'}, .shift=new TypeCode{.type=CHAR, .code=')'}, .alt=new TypeCode{.type=CHAR, .code=']'}, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 32 - 9
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x07}, .none=new TypeCode{.type=CHAR, .code='6'}, .shift=new TypeCode{.type=CHAR, .code='\''}, .alt=new TypeCode{.type=CHAR, .code='}'}, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 33 - 6
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x04}, .none=new TypeCode{.type=CHAR, .code='3'}, .shift=new TypeCode{.type=CHAR, .code='#'}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 34 - 3
    (AsciiMap) {.scancode = (Scancode) {.special = 0xE0, .code = 0x40}, .none=new TypeCode{.type=EVENT, .code=KB_EVENT_ARROWRIGHT}, .shift=new TypeCode{.type=EVENT, .code=KB_EVENT_FUNC6}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 35 - ARROW_RIGHT
    (AsciiMap) {.scancode = (Scancode) {.special = 0, .code = 0x0E}, .none=new TypeCode{.type=CHAR, .code=0x08}, .shift=new TypeCode{.type=EVENT, .code=KB_EVENT_FUNC3}, .alt=NULL, .strg=NULL, .shiftalt=NULL, .altstrg=NULL, .strgshift=NULL, .strgaltshift=NULL}, // 37 - BACKSPACE
    (AsciiMap) {.scancode = (Scancode) {.special = 0xE0, .code = 0x5E}, .none=new TypeCode{.type=EVENT, .code=KB_EVENT_ON}, .shift=new TypeCode{.type=EVENT, .code=KB_EVENT_ON}, .alt=new TypeCode{.type=EVENT, .code=KB_EVENT_ON}, .strg=new TypeCode{.type=EVENT, .code=KB_EVENT_ON}, .shiftalt=new TypeCode{.type=EVENT, .code=KB_EVENT_ON}, .altstrg=new TypeCode{.type=EVENT, .code=KB_EVENT_ON}, .strgshift=new TypeCode{.type=EVENT, .code=KB_EVENT_ON}, .strgaltshift=new TypeCode{.type=EVENT, .code=KB_EVENT_ON}} // 3C - ON
};
